# Generated by Django 3.2.13 on 2022-05-04 05:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje', models.CharField(max_length=250)),
                ('fecha', models.DateTimeField()),
                ('de', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='de', to=settings.AUTH_USER_MODEL)),
                ('para', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='para', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Entrada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=250)),
                ('mensaje', models.TextField()),
                ('fecha', models.DateTimeField()),
                ('subtitulo', models.CharField(max_length=250)),
                ('imagen', models.ImageField(upload_to='')),
                ('autor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='autor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
