# Generated by Django 3.2.13 on 2022-05-08 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muestro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='avatar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
